version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: tds_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: tds
      MYSQL_TCP_PORT: "3306"
    ports:
      - "3306:3306"
    expose:
      - "3306"